//@version=6
indicator("Gann Square of 9 Lines EZP", shorttitle="Gann Square of 9 Lines EZP", overlay=true, max_lines_count=500)

src = input.source(close, "Source")
base = input.float(1.00, title="Base Value", minval=0.0000001, confirm=true)
showGannLines = input.bool(true, "Show Gann Lines")

var float[] supportMultipliers = array.from(0.02, 0.04, 0.06, 0.08, 0.11, 0.15, 0.19, 0.23, 0.28, 0.34, 0.40, 0.46, 0.53, 0.61, 0.69, 0.77, 0.86, 0.96, 1.06, 1.16, 1.27, 1.39, 1.51, 1.63, 1.76, 1.90, 2.04, 2.18, 2.33, 2.49, 2.65, 2.81, 2.98, 3.16, 3.34, 3.52, 3.71, 3.91, 4.11, 4.31, 4.52, 4.74, 4.96, 5.18, 5.41, 5.65, 5.89, 6.13, 6.38, 6.64, 6.90, 7.16, 7.43, 7.71, 7.99, 8.27, 8.56, 8.86, 9.16, 9.46, 9.77, 10.09, 10.41, 10.73, 11.06, 11.40, 11.74, 12.08)
var float[] resistanceMultipliers = array.from(0.03, 0.05, 0.07, 0.09, 0.13, 0.17, 0.21, 0.25, 0.31, 0.37, 0.43, 0.49, 0.57, 0.65, 0.73, 0.81, 0.91, 1.01, 1.11, 1.21, 1.33, 1.45, 1.57, 1.69, 1.83, 1.97, 2.11, 2.25, 2.41, 2.57, 2.73, 2.89, 3.07, 3.25, 3.43, 3.61, 3.81, 4.01, 4.21, 4.41, 4.63, 4.85, 5.07, 5.29, 5.53, 5.77, 6.01, 6.25, 6.51, 6.77, 7.03, 7.29, 7.57, 7.85, 8.13, 8.41, 8.71, 9.01, 9.31, 9.61, 9.93, 10.25, 10.57, 10.89, 11.23, 11.57, 11.91, 12.25)

var line[] supportLines = array.new_line()
var line[] resistanceLines = array.new_line()

createLines(float[] multipliers, line[] lineStore, color lineColor) =>
    for i = 0 to array.size(multipliers) - 1
        level = base * array.get(multipliers, i)
        lineId = line.new(bar_index - 1, level, bar_index, level, xloc=xloc.bar_index, extend=extend.both, color=lineColor, width=1)
        array.push(lineStore, lineId)

updateLines(float[] multipliers, line[] lineStore) =>
    for i = 0 to array.size(lineStore) - 1
        level = base * array.get(multipliers, i)
        lineId = array.get(lineStore, i)
        line.set_y1(lineId, level)
        line.set_y2(lineId, level)

deleteLines(line[] lineStore) =>
    for i = 0 to array.size(lineStore) - 1
        line.delete(array.get(lineStore, i))
    array.clear(lineStore)

if showGannLines
    if array.size(supportLines) == 0
        createLines(supportMultipliers, supportLines, color.red)
    if array.size(resistanceLines) == 0
        createLines(resistanceMultipliers, resistanceLines, color.blue)

    updateLines(supportMultipliers, supportLines)
    updateLines(resistanceMultipliers, resistanceLines)
else
    if array.size(supportLines) > 0
        deleteLines(supportLines)
    if array.size(resistanceLines) > 0
        deleteLines(resistanceLines)

plot(src, color=color.new(color.black, 100), editable=false)
